name: deploy_develop

on:
  push:
    branches:
      - develop

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen del backend
        run: |
          docker build -t pavelphdevop/backend-mod3:latest

      - name: Autenticando en dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Publicando imagen al dockerhub.....
        run: |
          docker push pavelphdevop/backend-mod3:latest
  
  deploy-k8:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
      
      - name: Configurar kubectl....
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.CLUSTER_KUBE_CONFIG_K8 }}
        with:
          args: apply -f k8local-deployment-con-mysql.yaml